# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('price', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.Item'),
        ),
        migrations.AddField(
            model_name='gift',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.Person'),
        ),
    ]
